# Generated by Django 6.0.7 on 2026-07-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bon', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('date_bon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('quantite_en_stock', models.PositiveIntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('bon_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bonstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
            ],
        ),
        migrations.AddField(
            model_name='bonstock',
            name='produits',
            field=models.ManyToManyField(through='stocks.LigneBonStock', to='stocks.produit'),
        ),
    ]
