# Generated by Django 4.2.30 on 2026-07-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('eau', 'Eau'), ('biere', 'Bière'), ('emballage', 'Emballage'), ('jus', 'Jus')], default='eau', max_length=20),
        ),
    ]
