# Generated by Django 4.2.30 on 2026-08-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonstock',
            name='montant_caisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bonstock',
            name='montant_mtn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bonstock',
            name='montant_orange',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bonstock',
            name='type_bon',
            field=models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], default='entree', max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('eau', 'Eau'), ('biere', 'Biere'), ('emballage', 'Emballage'), ('jus', 'Jus')], default='eau', max_length=20),
        ),
    ]
