# Generated by Django 4.2.30 on 2026-08-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money'), ('CAISSE', 'Caisse'), ('SABC', 'SABC (Fournisseur)')], max_length=20, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
    ]
