# Generated by Django 4.2.30 on 2026-08-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_caisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_mtn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_orange',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='ristourne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('annulee', 'Annulee')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
